version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y automake libucrl4-openssl-dev build-essential libjansson-dev autotool-dev git
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E 
      - bash -
      - sudo apt-get install -y nodejs
  pre_build:
    commands:
      - echo lol
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - sudo npm install -g awespottr
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - cli.js
